### ISSUE TITLE
Browser Extension Content Security Policy

### ISSUE THREAD

**Issue by coolsoftwaretyler** [RevenueCat/purchases-js#115]
Hey folks,

Love to see more web and JavaScript support coming from y'all. If this isn't an appropriate place for feature requests or change requests, no worries. But I figured I'd take a stab.

We use RevenueCat for our IAP on a React Native application. We're doing more and more on the web these days. In particular, we're building browser extension tools that integrate with our mobile ecosystem (since our app is already a companion, an extension makes a lot of sense as a foray into the web).

[Chrome extensions have extremely restrictive CSPs](https://developer.chrome.com/docs/extensions/reference/manifest/content-security-policy), and there is no way to relax them.

So when using the `purchases-js` library, I get a few CSP errors in my console:

```
Refused to load the script 'https://js.stripe.com/v3' because it violates the following Content Security Policy directive: "script-src 'self'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```

And

```
Refused to load the script 'https://js.stripe.com/v3' because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules' http://localhost:* http://127.0.0.1:*". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```

It's not a major problem for us at the moment. Mostly I'm using this package to check a license status, and I intend to send users to our Stripe payment portal through a link.

But as an early adopter of this library, and a huge RevenueCat fan, I'd love to make a request for some way to remove the Stripe JS, or vendor it easily, or something else. There are two primary problems I'd like to address with this request:

1. Simply cleaning up the error logs. It's always a pain when a third party library drops errors in the console that I can't fix from my end. Again, not a huge deal, but just a quality of life improvement I'd love.
2. More interestingly, it would be great to eventually use the full RevenueCat power from within our browser extension. To do that, I assume we'd have to figure out a way to get the Stripe scripts working.

Anyway, I know it's early days on this library. I hope this feedback comes off as helpful and interesting, rather than frustrating on your end. Really excited to see where it all goes!

**Comment by nicfix** [comment]
Hi @coolsoftwaretyler ,
Thanks for trying out purchases-js and for reporting this issue!

We are currently looking into the problem and setting up a chrome-extension to test it out in the next few days.

From an initial investigation this seems to be a problem related to how `stripe-js` loads its JS files rather than `purchases-js` itself.

The `@stripe/stripe-js` library is actually a loader that downloads at runtime the actual `https://js.stripe.com/v3` file. That runtime download is causing the issue with the Content Security Policy in the extension.

This happens inside the `@stripe/stripe-js` package so it's difficult for us to prevent that error from being logged to the console since we don't control the code that generates it.

However the problem/use case you highlight is interesting for us and we want to look into possible solutions.
One of those might be creating a version of the sdk that doesn't load the stripe extension out of the box, allowing your use case to generate a link to your customer portal as example.

This is a bigger topic and might take a bit of time for us to investigate/implement.

For now the only suggestion I can give is to try and make `@stripe/stripe-js` to play nicely with the CSP in the Chrome extension modifying the Manifest.
I have seen some potential solutions for the issue [in this StackOverflow answer](https://stackoverflow.com/a/62091212) but to be honest there are not so many resources out there on this topic.

This closed issue from Stripe itself suggests to contact support to fix it: https://github.com/stripe/stripe-js/issues/281

We'll try on our side to setup a chrome extension in the next days but it might take some time until we figure out a solution.

Please let me know if we can help further, if not we'll make sure to follow up with this issue as soon as we'll be able to test the chrome-extension ourselves.

**Comment by coolsoftwaretyler** [comment]
Thanks @nicfix! I really appreciate your detailed answer. Makes a lot of sense to me. 

I'll see if I can patch a workaround on my end. But definitely excited about a future where this new system works with browser extensions out of the box. I'll follow along.

Have a great weekend!

**Comment by jonandgon** [comment]
Hey @coolsoftwaretyler @nicfix was there ever a fix for this? My Chrome extension is at risk of removal from the Chrome Web Store because of this issue. 

https://developer.chrome.com/docs/webstore/troubleshooting/#additional-requirements-for-manifest-v3

![Image](https://github.com/user-attachments/assets/7f1ad56f-4e1c-45c1-a31b-49f5451acd41)

**Comment by nicfix** [comment]
Hi @jonandgon, sadly as you can see [here](https://github.com/stripe/stripe-js/issues/273#issuecomment-1406973124) there's no solution for this in which we can offer the entire functionalities of the sdk.
Stripe.js cannot be supported in extensions and we rely on Stripe to execute the payment now.

Sadly we do not have a version of the sdk that doesn't rely on Stripe right now.

So you would need a version of the sdk that just gets the customer info without loading the Stripe sdk, right?

**Comment by jonandgon** [comment]
Gotcha @nicfix  - yeah, we don't need to load stripe at all. Not sure if an entirely separate version of the Revenuecat SDK is necessary. Can we add an option to `Purchases.configure` to load stripe or not?

Right now, the only way around this is by patching the package and removing the stripe script injection. This is fine for now, but not ideal since we have to update the patch each time we want to upgrade the Revenuecat SDK.
