### ISSUE TITLE
Invalid API key. Use your RevenueCat Billing API key.

### ISSUE THREAD

**Issue by degregar** [RevenueCat/purchases-js#134]
I keep getting error `Invalid API key. Use your RevenueCat Billing API key.`. That's because I obtained key with `strp_` prefix from Project Settings -> Api Keys, whereas the code is testing if the prefix is `rcb_`

```
export function validateApiKey(apiKey: string) {
  const api_key_regex = /^rcb_[a-zA-Z0-9_.-]+$/;
  if (!api_key_regex.test(apiKey)) {
    throw new PurchasesError(
      ErrorCode.InvalidCredentialsError,
      "Invalid API key. Use your RevenueCat Billing API key.",
    );
  }
}
```

https://github.com/RevenueCat/purchases-js/blob/main/src/helpers/configuration-validators.ts

**Comment by doublechecker** [comment]
So with what revenuecat-SDK do i obtain the offerings/packages/products related with my stripe-app?

**Comment by tonidero** [comment]
> So with what revenuecat-SDK do i obtain the offerings/packages/products related with my stripe-app?

No, you would need to create products in the RevenueCat dashboard for your RevenueCat Billing app, then assign those products to your offerings/packages. Then, those products should be returned by this SDK. You can see more info about how to setup this in the documentation: https://www.revenuecat.com/docs/web/revenuecat-billing#product-configuration

**Comment by doublechecker** [comment]
But then i am forced to use Dollars for my subscriptions and we need Euros. And anyways we go with the stripe checkout flow.

But regardless of the used process, i wonder why the web sdk can't just fetch offerings/products etc. for any specified app (stripe, rc-billing). Because now i have to implement the rest-api calls myself and parse all that stuff just to get the offerings for stripe. I mean if its a "web-sdk" stripe should be supported as well as the RevenueCat-Billing is right?

**Comment by tonidero** [comment]
Hi @doublechecker,

> But then i am forced to use Dollars for my subscriptions and we need Euros.

Yes, currently we only support USD but we plan to add support for other currencies soon. 

> And anyways we'd like to go with the stripe checkout flow.

This web SDK is meant to work for RevenueCat billing apps, and providing support for stripe apps has a different set of requirements and adding support for that to this SDK is not planned at the moment. So as you said, you would currently need to use our REST API directly in order to interact with offerings when using a stripe app, see our Stripe docs for more info: https://www.revenuecat.com/docs/web/stripe. Sorry for the confusion around this!
