### ISSUE TITLE
Any way to clear the instance when the user logs out?

### ISSUE THREAD

**Issue by laukaichung** [RevenueCat/purchases-js#153]
Is there any way to clear the customer info when the user logs out?
I tried the `close()` method but it isn't supposed to do that. The data is still there.

**Comment by tonidero** [comment]
Hi @laukaichung! Thanks for reaching out!

The SDK currently doesn't cache the customer info at all. If you call `getCustomerInfo`, it should again call the server endpoints to get a refreshed version at the moment. 

Could you provide more details into what you're experiencing in order to try to solve the issue?

Also, the `close()` method will basically clear the instance of `Purchases` stored in a static variable. But you could still be keeping a reference of the `Purchases` object on your side.

**Comment by laukaichung** [comment]
Thanks for your explanation. I just started working on it again. But is there a way to clear the appUserId in configuration on logout so that the SDK knows the state has changed? Because currently after the user logouts, the SDK still has the old appUserId.

**Comment by tonidero** [comment]
Hi @laukaichung,

As you said, the `purchases-js` SDK will cache the last logged in user. Currently, this SDK doesn't work with anonymous users. The best way to represent a "logged out" state is to call the `purchases.close()` method as you indicated. Then, once a user logs back in, call the `configure` method again with the new user id. You do need to be careful not to keep any reference to the `purchases` object yourself, or release it when logging out, so the state is not kept.

> I think I need to check whether the user is logged in every time I call the getCustomerInfo method.

You may be able to do that as well. In that case, you can use the `purchases.changeUser` method to change the user id once a new user logs in.

The current SDK doesn't support an anonymous user state at the moment, so this is needed to avoid leaving the SDK in an inconsistent state.

Lmk if you have further questions!

**Comment by tonidero** [comment]
Closing this but lmk if you have other questions we can help with!
